// GENERATED by scripts/sync-offerings.mjs from config/money_os.yaml. Do not edit; edit config/money_os.yaml.
export const OS_CONFIG = {
  "timezone": "America/New_York",
  "budgets": {
    "per_day_usd": 2,
    "per_turn_usd": 0.1,
    "per_research_run_usd": 0.25,
    "per_experiment_usd": 1
  },
  "tasks": {
    "jarvis_chat": {
      "role": "small",
      "max_tokens": 700,
      "max_rounds": 5
    }
  },
  "prices": {
    "claude-haiku-4-5-20251001": {
      "input": 1,
      "output": 5,
      "cache_write": 1.25,
      "cache_read": 0.1
    },
    "claude-opus-5-5": {
      "input": 4,
      "output": 20,
      "cache_write": 5,
      "cache_read": 0.2
    }
  },
  "web_search_usd": null,
  "cache": {
    "research_ttl_days": 14
  },
  "score": {
    "weights": {
      "demand": 3,
      "monetization": 2.5,
      "speed": 2,
      "trend": 1.5,
      "recurring": 1.5,
      "competition": 1.5,
      "acquisition_difficulty": 1.5,
      "affiliate": 1,
      "content": 1,
      "automation": 1,
      "startup_cost": 1,
      "tech_difficulty": 1,
      "retention": 1,
      "market_size": 1,
      "defensibility": 0.5
    },
    "inverted": [
      "competition",
      "startup_cost",
      "tech_difficulty",
      "acquisition_difficulty"
    ],
    "confidence": {
      "evidence_target": 6,
      "domain_target": 4,
      "recency_days": 90
    },
    "labels": {
      "high_score_min": 7,
      "strong_evidence": {
        "min_confidence": 0.6,
        "min_domains": 3
      },
      "fast_validation": {
        "max_validation_difficulty": 3,
        "max_days_to_first_dollar": 14
      }
    }
  }
} as const;
