// GENERATED by scripts/sync-offerings.mjs from config/money_os.yaml. Do not edit; edit config/money_os.yaml.
export const OS_CONFIG = {
  "timezone": "America/New_York",
  "budgets": {
    "per_day_usd": 2,
    "per_turn_usd": 0.1,
    "per_research_run_usd": 0.25,
    "per_experiment_usd": 1
  },
  "editable_budgets": {
    "per_day_usd": {
      "min": 0.25,
      "max": 10
    },
    "per_turn_usd": {
      "min": 0.02,
      "max": 0.5
    },
    "per_research_run_usd": {
      "min": 0.2,
      "max": 1
    }
  },
  "tasks": {
    "jarvis_chat": {
      "role": "small",
      "max_tokens": 700,
      "max_rounds": 5
    }
  },
  "prices": {
    "claude-haiku-4-5-20251001": {
      "input": 1,
      "output": 5,
      "cache_write": 1.25,
      "cache_read": 0.1
    },
    "claude-opus-5-5": {
      "input": 4,
      "output": 20,
      "cache_write": 5,
      "cache_read": 0.2
    }
  },
  "web_search_usd": 0.01,
  "cache": {
    "research_ttl_days": 14
  },
  "score": {
    "weights": {
      "demand": 3,
      "monetization": 2.5,
      "speed": 2,
      "trend": 1.5,
      "recurring": 1.5,
      "competition": 1.5,
      "acquisition_difficulty": 1.5,
      "affiliate": 1,
      "content": 1,
      "automation": 1,
      "startup_cost": 1,
      "tech_difficulty": 1,
      "retention": 1,
      "market_size": 1,
      "defensibility": 0.5
    },
    "inverted": [
      "competition",
      "startup_cost",
      "tech_difficulty",
      "acquisition_difficulty"
    ],
    "confidence": {
      "evidence_target": 6,
      "domain_target": 4,
      "recency_days": 90
    },
    "labels": {
      "high_score_min": 7,
      "strong_evidence": {
        "min_confidence": 0.6,
        "min_domains": 3
      },
      "fast_validation": {
        "max_validation_difficulty": 3,
        "max_days_to_first_dollar": 14
      }
    }
  },
  "radar": {
    "role": "small",
    "max_searches": 2,
    "max_opportunities": 4,
    "max_tokens": 2500,
    "categories": {
      "ai_tools": "AI tools and AI utilities that individuals or small businesses pay for",
      "ai_income": "ways people earn income using AI (services, freelancing, side businesses)",
      "ai_shopping": "AI shopping assistants, deal finding and product comparison",
      "affiliate": "affiliate programs and affiliate content businesses with recurring commissions",
      "tiktok_commerce": "TikTok Shop and short-video commerce",
      "digital_products": "digital products (templates, guides, courses, printables) that sell online",
      "creator_tools": "tools and services for content creators",
      "job_income_tools": "job search, resume, interview and income tools for workers",
      "media_newsletters": "niche media and paid or sponsored newsletters",
      "micro_saas": "micro-SaaS for small, underserved niches and emerging consumer problems"
    }
  },
  "research": {
    "role": "small",
    "max_searches": 5,
    "max_tokens": 3000
  },
  "social_radar": {
    "cache_hours": 24,
    "youtube": {
      "daily_units_cap": 2000,
      "window_days": 30,
      "per_query": 25,
      "region": "US",
      "language": "en",
      "queries": [
        "side hustle ideas",
        "make money online",
        "passive income ideas",
        "make money with AI",
        "online business ideas",
        "digital products to sell",
        "work from home jobs",
        "small business ideas"
      ]
    },
    "analysis": {
      "role": "small",
      "max_tokens": 2000,
      "max_videos": 40,
      "max_opportunities": 6
    }
  }
} as const;
