// GENERATED by scripts/sync-offerings.mjs from config/money_os.yaml. Do not edit; edit config/money_os.yaml.
export const OS_CONFIG = {
  "timezone": "America/New_York",
  "budgets": {
    "per_day_usd": 2,
    "per_turn_usd": 0.1,
    "per_research_run_usd": 0.25,
    "per_experiment_usd": 1
  },
  "tasks": {
    "jarvis_chat": {
      "role": "small",
      "max_tokens": 700,
      "max_rounds": 5
    }
  },
  "prices": {
    "claude-haiku-4-5-20251001": {
      "input": 1,
      "output": 5,
      "cache_write": 1.25,
      "cache_read": 0.1
    },
    "claude-opus-5-5": {
      "input": 4,
      "output": 20,
      "cache_write": 5,
      "cache_read": 0.2
    }
  },
  "web_search_usd": null,
  "cache": {
    "research_ttl_days": 14
  }
} as const;
