// GENERATED by scripts/sync-offerings.mjs from config/models.yaml. Do not edit; edit config/models.yaml.
export const MODELS_CONFIG = {
  "models": {
    "small": "claude-haiku-4-5-20251001",
    "audit": "claude-opus-5-5"
  },
  "tts": {
    "elevenlabs": "eleven_turbo_v2_5"
  },
  "allowed": {
    "voice": [
      "small"
    ],
    "notify": [
      "small"
    ],
    "leadgen": [
      "small"
    ],
    "jarvis": [
      "small"
    ],
    "audit": [
      "audit",
      "small"
    ]
  }
} as const;
